services:
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: ./Dockerfile
  #   command: bun run dev
  #   depends_on:
  #     - clickhouse
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./app
  #         target: /app
  #         ignore:
  #           - node_modules/
  #           - migrations/
  #           - secrets/

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    volumes:
      - ./.clickhouse:/var/lib/clickhouse/
      - clickhouse_logs:/var/log/clickhouse-server/
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB_NAME}
      CLICKHOUSE_USER: ${CLICKHOUSE_USERNAME}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "5521:5521"
    depends_on:
      - clickhouse
    environment:
      VITE_CLICKHOUSE_URL: ${CLICKHOUSE_HOST}
      VITE_CLICKHOUSE_USER: ${CLICKHOUSE_USERNAME}
      VITE_CLICKHOUSE_PASS: ${CLICKHOUSE_PASSWORD}
      VITE_CLICKHOUSE_USE_ADVANCED: true

volumes:
  clickhouse_logs:
